#ifndef AVP_RIF_H
#define AVP_RIF_H


#define AVP_COMPRESSED_RIF_IDENTIFIER "REBCRIF1"
#define AVP_UNRECOGNIZED_RIF_IDENTIFIER "REBINFF2"

#define AVP_CHUNK_FAILED_ON_LOAD -1
#define AVP_CHUNK_FAILED_ON_LOAD_NOT_RECOGNISED -2
#define AVP_CHUNK_FAILED_ON_WRITE -3
#define AVP_CHECK_FAILED_NOT_OPEN -4

void AVP_Rif_Load(const char* path);


#endif

